# Generated by Django 6.0.8 on 2026-09-24 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_slug', models.CharField(max_length=100)),
                ('pipeline_slug', models.CharField(max_length=100)),
                ('permit_file_sha256', models.CharField(blank=True, max_length=64)),
                ('pipeline_file_sha256', models.CharField(blank=True, max_length=64)),
                ('period', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('schema_version', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RejectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=32)),
                ('record_id', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_entries', to='validation.validationrun')),
            ],
        ),
        migrations.CreateModel(
            name='ProvenanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=32)),
                ('record_id', models.CharField(max_length=64)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('note', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance_entries', to='validation.validationrun')),
            ],
        ),
        migrations.CreateModel(
            name='LimitResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfall', models.IntegerField()),
                ('parameter', models.CharField(max_length=64)),
                ('clause', models.CharField(max_length=32)),
                ('sample_ids', models.JSONField()),
                ('sample_values', models.JSONField()),
                ('computed_value', models.CharField(max_length=64)),
                ('threshold', models.CharField(max_length=64)),
                ('comparison', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('reason', models.TextField()),
                ('gemini_explanation', models.TextField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='validation.validationrun')),
            ],
        ),
    ]
